// Generated by CoffeeScript 1.6.2
(function() {
  var craw, onPopEmpty, onPopFirst5Levels, onPopFirstLevel, start, startOpts;

  craw = require("./crawler");

  startOpts = function(opts, onPop) {
    return craw.start(opts, onPop, function(err) {
      return console.log("started", err);
    });
  };

  start = function(onPop) {
    var opts;

    opts = {
      amqp: {
        config: {
          url: "amqp://localhost"
        },
        queue: "baio-crawler"
      },
      log: {
        level: 0,
        write: function(level, code, msg) {
          return console.log(level, code, msg);
        }
      }
    };
    return startOpts(opts, onPop);
  };

  onPopEmpty = function(level, body, done) {
    console.log("onPopEmpty", level);
    return done(null, null);
  };

  onPopFirstLevel = function(level, body, done) {
    console.log("onPopFirstLevel", level);
    if (level === -1) {
      return done(null, ["twitter.com"]);
    } else {
      return done(null, null);
    }
  };

  onPopFirst5Levels = function(level, body, done) {
    console.log("onPopFirst5Levels", level);
    if (level < 5) {
      return done(null, ["twitter.com"]);
    } else {
      return done(null, null);
    }
  };

  start(onPopFirstLevel);

}).call(this);

/*
//@ sourceMappingURL=crawler.test.map
*/
